name: Build SDL Project for ARM

on: [push, pull_request]

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cross-compiler and SDL2 dev
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf pkg-config libsdl2-dev:armhf
      - name: Build for ARM
        run: |
          arm-linux-gnueabihf-gcc main.c -o sdl2_text_example_arm $(pkg-config --cflags --libs sdl2)
      - name: Archive ARM build
        uses: actions/upload-artifact@v4
        with:
          name: sdl2_text_example_arm
          path: sdl2_text_example_arm