name: SDL2 ARM Build

on: [push]

jobs:
  build-arm:
    runs-on: ubuntu-24.04-arm  # Native ARM64 runner!

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev gcc make

      - name: Build
        run: |
          gcc -g main.c -o sdl_app_arm $(pkg-config --cflags --libs sdl2 SDL2_ttf)

      - name: Upload ARM binary
        uses: actions/upload-artifact@v4
        with:
          name: sdl_app_arm
          path: sdl_app_arm
