name: SDL2 ARM Build

on: [push]

jobs:
  build-arm:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Build with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: debian:buster
          options: |
            --platform linux/arm
            -v ${{ github.workspace }}:/src
          run: |
            dpkg --add-architecture armhf
            apt-get update
            apt-get install -y \
                gcc-arm-linux-gnueabihf \
                libsdl1.2-dev:armhf \
                libsdl-ttf2.0-dev:armhf

            cd /src
            arm-linux-gnueabihf-gcc -g main.c -o sdl_app_arm $(pkg-config --cflags -lsdl2 -lSDL2_ttf)

      - name: Upload ARM binary
        uses: actions/upload-artifact@v4
        with:
          name: sdl_app_arm
          path: sdl_app_arm
