name: SDL2 ARM Build

on: [push]

jobs:
  build-arm:
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              libsdl2-dev \
              libsdl2-ttf-dev \
              gcc \
              make

      - name: Build
        run: |
          gcc -g main.c -o app $(pkg-config --cflags --libs sdl2 SDL2_ttf)

      - name: Upload ARM binary
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app
