name: SDL1.2 ARM Build

on: [push]

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Build with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: debian:buster
          options: |
            --platform linux/arm
            -v ${{ github.workspace }}:/src
          run: |
            # Add ARM architecture and update
            dpkg --add-architecture armhf
            apt-get update

            # Install minimal dependencies for KMSDRM/fbdev
            apt-get install -y \
                gcc-arm-linux-gnueabihf \
                libsdl1.2-dev:armhf \
                libsdl-ttf2.0-dev:armhf \
                libgbm-dev:armhf \
                libdrm-dev:armhf

            # Build with dynamic linking
            cd /src
            arm-linux-gnueabihf-gcc -g main.c -o sdl_app_arm \
                $(sdl-config --cflags --libs) \
                -lSDL_ttf \
                -ldrm \
                -lgbm \
                -lm

      - name: Upload ARM binary
        uses: actions/upload-artifact@v4
        with:
          name: sdl_app_arm
          path: sdl_app_arm
