name: SDL2 ARM Build

on: [push]

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Build with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: debian:bookworm
          options: |
            --platform linux/arm
            -v ${{ github.workspace }}:/src
          run: |
            apt-get update && apt-get install -y \
                gcc-arm-linux-gnueabihf \
                libsdl2-dev:armhf \
                libsdl2-ttf-dev:armhf \
                pkg-config
            cd /src
            arm-linux-gnueabihf-gcc main.c -o sdl_app_arm $(pkg-config --cflags --libs sdl2 SDL2_ttf)

      - name: Upload ARM binary
        uses: actions/upload-artifact@v4
        with:
          name: sdl_app_arm
          path: sdl_app_arm
