name: Build SDL Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: libsdl-org/setup-sdl@main
        with:
          install-linux-dependencies: true
          version: 2-latest
      - name: Build with gcc
        run: |
          gcc main.c -o sdl_bitmap_font_example $(pkg-config --cflags --libs sdl2)
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: sdl_bitmap_font_example
          path: sdl_bitmap_font_example
