name: SDL1.2 ARM Build

on: [push]

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Build with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: debian:buster
          options: |
            --platform linux/arm
            -v ${{ github.workspace }}:/src
          run: |
            # Add ARM architecture and update
            dpkg --add-architecture armhf
            apt-get update

            # Install required libraries (static and dynamic)
            apt-get install -y \
                gcc-arm-linux-gnueabihf \
                libsdl1.2-dev:armhf \
                libsdl-ttf2.0-dev:armhf \
                libasound2-dev:armhf \
                libpulse-dev:armhf \
                libx11-dev:armhf \
                libxext-dev:armhf \
                libxrender-dev:armhf \
                libxrandr-dev:armhf \
                libcaca-dev:armhf \
                libgl1-mesa-dev:armhf \
                libdbus-1-dev:armhf \
                libasound2-dev:armhf-static \
                libpulse-dev:armhf-static \
                libx11-dev:armhf-static

            # Fix missing symlinks for static libraries
            ln -s /usr/lib/arm-linux-gnueabihf/libasound.a /usr/lib/arm-linux-gnueabihf/libasound2.a || true
            ln -s /usr/lib/arm-linux-gnueabihf/libpulse.a /usr/lib/arm-linux-gnueabihf/libpulse-simple.a || true

            # Build with dynamic linking
            cd /src
            arm-linux-gnueabihf-gcc main.c -o sdl_app_arm \
                $(sdl-config --cflags --libs) \
                -lSDL_ttf \
                -lasound \
                -lpulse \
                -lX11 \
                -lXext \
                -lXrender \
                -lXrandr \
                -lcaca \
                -ldbus-1 \
                -lm

      - name: Upload ARM binary
        uses: actions/upload-artifact@v4
        with:
          name: sdl_app_arm
          path: sdl_app_arm
